branch-defaults:
  master:
    default_platform: Docker
    environment: LoboBackend
    group-suffix: null
  release:
    default_platform: Node.js
    environment: LoboBackend
    group_suffix: null
global:
  application_name: lobo-backend
  default_ec2_keyname: LoboKeyPair
  default_region: us-east-1
  profile: eb-cli
  sc: git
